### PR TITLE
bump PHP version to 8.1 and update Laravel to 9.0

### PR DESCRIPTION
**Pull request by 50bhan**

### CODE REVIEW

**Comment by mohammad-fouladgar** [comment]
@50bhan 
As you know, we have to move the `lang` directory to the root directory app.

https://laravel.com/docs/9.x/upgrade#the-lang-directory

**Comment by 50bhan** [comment]
@mohammad-fouladgar Could you please run the workflow to see if everything is working?

**Comment by mohammad-fouladgar** [comment]
@50bhan Could you PR again, please? I had to revert this PR. Because we need a version for previous PHP and Laravel versions. After releasing the first version I will merge this PR with the master. Thanks in advance.

**Comment by 50bhan** [comment]
@mohammad-fouladgar No worries! New PR -> https://github.com/mohammad-fouladgar/laravel-otp/pull/4

**Pull request merged**
